on:
  repository_dispatch:
    types: [ test-on-demand ]
  workflow_dispatch:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  prepare-device-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: get-matrix
        with:
          script: |
            const devices = {include:[
                {
                  os:'android',
                  device:'device-1',
                  message: 'message 1'
                },
                {
                  os:'ios',
                  device:'device-2',
                  message: 'message 2'
                },
                {
                  os:'ios',
                  device:'device-3',
                  message: 'message 3'
                },
                {
                  os:'ios',
                  device:'device-4',
                  message: 'message 3'
                }
              ]
            .filter(config => config.message.toLowerCase()==context.payload?.inputs?.message.toLowerCase())
            }
            console.log(devices)
            console.log(context)
            return devices

  test:
    runs-on: ubuntu-latest
    needs: prepare-device-matrix
    environment:
      name: test_environment
      url: https://github.com
    strategy:
      matrix:
        include:
          - os: 'android'
            device: 'device-1'
            message: 'message 1'
          - os: 'ios'
            device: 'device-2'
            message: 'message 2'
          - os: 'ios'
            device: 'device-3'
            message: 'message 3'
          - os: 'ios'
            device: 'device-4'
            message: 'message 3'
    env:
      message: ${{ matrix.message }}
    if: env.message == inputs.message
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ukostas/dispatch-demo-support-flow
          ref: main
      - env:
          MESSAGE: ${{ github.event.client_payload.message || github.event.inputs.message || inputs.message }}
        run: |
          echo 'github.event.client_payload.message message is: ${{github.event.client_payload.message}}'
          echo 'github.event.inputs.message message is: ${{github.event.inputs.message}}'
          echo 'inputs.message message is: ${{inputs.message}}'
