on:
  repository_dispatch:
    types: [ test-on-demand ]
  workflow_dispatch:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  prepare-support-tools:
    runs-on: ubuntu-latest
    steps:
      - run: echo preparing ...

  test:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: test_environment
      url: https://github.com
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ukostas/dispatch-demo-support-flow
          ref: main
          path: dispatch-demo-support-flow
      - env:
          MESSAGE: ${{ github.event.client_payload.message | github.event.inputs.message | inputs.message }}
        run: "echo test message is: $MESSAGE"
      - run: exit 1