on:
  repository_dispatch:
    types: [ test-on-demand ]
  workflow_dispatch:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo preparing ...

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message | github.event.inputs.message | inputs.message }}
        run: "echo test message is: $MESSAGE"
      - run: exit 1